# Generated by Django 4.2 on 2025-01-18 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_subscripcion_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscripcion',
            old_name='CantidadClases',
            new_name='dias',
        ),
        migrations.RenameField(
            model_name='subscripcion',
            old_name='FechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='subscripcion',
            old_name='FechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='subscripcion',
            old_name='Monto',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='subscripcion',
            old_name='Planes',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='subscripcion',
            old_name='Socios',
            new_name='socio',
        ),
        migrations.AddField(
            model_name='planes',
            name='Dias',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.subscripcion')),
            ],
        ),
    ]
