# Generated by Django 5.1.6 on 2025-03-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_alter_subscripcion_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subscripcion',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='subscripcion',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscripcion',
            name='dias',
            field=models.IntegerField(null=True),
        ),
    ]
