# Generated by Django 5.1.6 on 2025-03-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0007_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngresoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_egreso', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.profesor')),
            ],
        ),
    ]
