# Generated by Django 5.1.6 on 2025-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0008_profesor_registroingresoegreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
