# Generated by Django 5.1.6 on 2025-03-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0009_socios_saldo_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='saldo_actual',
        ),
    ]
