# Generated by Django 5.1.6 on 2025-03-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0011_socios_saldo_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='subscripcion',
        ),
        migrations.AddField(
            model_name='pago',
            name='socio',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Aplicacion1.socios'),
            preserve_default=False,
        ),
    ]
