# Generated by Django 5.1.6 on 2025-06-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0012_remove_pago_subscripcion_pago_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion1.planes'),
        ),
    ]
